services:
  db:
    image: postgres:16
    container_name: orca-postgres
    restart: always
    environment:
      POSTGRES_USER: orca
      POSTGRES_PASSWORD: orca
      POSTGRES_DB: orcadata
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports: 
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orca -d orcadata"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: orca-adminer
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
    driver: local